#!/bin/bash

set -eo pipefail

DIST_DIR="target/hivemq-retained-message-query-extension"
ARTIFACTS_DIR="artifacts"

echo "Building"
mvn package -P TravisCI

echo "Packaging"
mkdir "${ARTIFACTS_DIR}"
cd "${DIST_DIR}"
echo {\"branch\": \"$TRAVIS_BRANCH\", \"commit\": \"$TRAVIS_COMMIT\", \"build\": $TRAVIS_BUILD_NUMBER} > build.json
zip -r -9 "../../${ARTIFACTS_DIR}/hivemq-retained-message-query-extension-${TRAVIS_BRANCH}.zip" *
tar czvf "../../${ARTIFACTS_DIR}/hivemq-retained-message-query-extension-${TRAVIS_BRANCH}.tar.gz" *
